minor style fixing
infoshareacademy/jfdzs2-ampf pull request #5
Opened 2018-02-18 19:16 UTC by soltykiewiczm

finalny i skończony feature z zespołem
bardzo proszę o bezwarunkowe zatwierdzenie pull request'a :)

2018-02-18 19:47 UTC, maciekmp requested changes
uwagi przekazane ustnie

2018-02-21 12:17 UTC, maciekmp requested changes
dla mobile nie ma praktycznie odstępu między social buttons a zdjęciem  kolejnego członka

2018-02-24 14:33 UTC, soltykiewiczm commented
reseolved conflict with an id of section team

2018-02-24 15:04 UTC, maciekmp commented on index.html
>          <div class="person col-xs-12 col-sm-4 col-md-4 col-xl-3">
co to col-xl-3???????

2018-02-24 15:23 UTC, maciekmp approved these changes

2018-02-24 15:24 UTC, merged