Final/Complete Feature Functions
infoshareacademy/jfdzs2-ampf pull request #8
Opened 2018-02-19 17:25 UTC by karoob

Finalna wersja sekcji funkce z 4 ikonami i krótkimi opisami.
Zmieniono:
- odległość pading dolny w celu zachowania odstępu kolejnej (następującej sekcji)
- uporządkowano kod html sekcji

2018-02-21 11:47 UTC, maciekmp requested changes
dla desktop nagłówek sekcji jest bliżej poprzedniej sekcji niż treści sprawdzanej, na mobile treść jest za wąska, na każdej rozdzielczości mam poziomy scroll. Reszta ok

2018-02-22 16:13 UTC, karoob commented
- Usunięto paddingi w wersji mobilnej ale pozostawiono w pozostałych
- Zwiększono padingi pomiędzy przyległymi sekcjami
- Skroll wynika z sekcji 'team' w związku z tym nie dokonano zmian,
- Wyedytowanio komentarze sekcji. Zostały albo usunięte albo zamienione na język angielski

2018-02-23 16:05 UTC, maciekmp commented
Dalej jest coś nie tak, kolumna z treścią funkcji powinna mieć xs-12 i bez modyfikacji powinien być padding z lewej i prawej krawędzie ekranu.

2018-02-23 22:29 UTC, karoob commented
Wyedytowano klasy bootstrapowe i usunięto edytowanie paddingów w ccs.

2018-02-24 12:02 UTC, maciekmp approved these changes
jest ok, brakuje .row pomiędzy gridami zewnętrznymi i wewnętrznymi

2018-02-24 12:47 UTC, merged