Feature nav - nawigacja i header finalna wersja
infoshareacademy/jfdzs2-ampf pull request #9
Opened 2018-02-20 20:25 UTC by skwirowski

# Ostatnie fixy, małe poprawki i uzupełnienie informacji.

* Dodane czcionki:
  - Lobster - logo
  - Montserrat - menu & nawigacja
  - Playfair Display - tekst nagłówka
* Dopasowane i wyśrodkowane elementy menu nawigacji w szerokościach mobilnych (z burgerem)
* changed hoover/active color to 
* Zmieniony kolor stanów hover i active w tekście loga i menu nawigacji na kolor zielony #29B200
* Dodane **id** do każdej głównej sekcji dla celów lokalizacyjnych menu nawigacji
  - #feature-info
  - #feature-functions
  - #feature-form
  - #feature-team
* Dodany fragment kodu CSS przed każdą główną sekcją strony - poprawka do offsetu występującego przy użyciu menu nawigacji (spowodowanego position: fixed dla paska menu)
* Drobne poprawki stylizacyjne w pliku CSS
* Dodany div z bootstrapową klasą _jumborton_ w skcji header - cel wyróżnienie nagłówka
* Dodany treść tekstowa headera
----
Jest to wersja ostateczna. Chciałbym, żebyś miał na uwadze to, że dodałem **#id** do każdej głównej sekcji. Nie wiem czy to ma wpływ na kolejność przyjmowania przez Ciebie pull requestów.
----
Pozdrawiam,
Paweł Skwirowski

2018-02-21 11:56 UTC, maciekmp requested changes
Bardzo ładnie to wygląda jednak nie możemy sobie pozwolić na więcej niż 2 czcionki i najlepiej gdyby były one ładowane za pomocą google fonts. Na emulowanym mobile mogę przesunąć stronę horyzontalnie, przed przesunięciem przycisk hamburger jest przy samym ekranie.

2018-02-21 21:14 UTC, skwirowski commented
# Poprawki naniesione. Usunięte lokalne pliki czcionek, dodane linki @import dla google fonts, dodany nowy obrazek z logo
* Wszystkie lokalne pliki z czcionkami zostały usunięte
* Dodane linki @import z czcionkami z google fonts - zlinkowane zostały tylko 3 niezbędne czcionki użyte w projekcie
  - Montserrat medium (500) normal,
  - Playfair Display regular (400) italic,
  - Playfair Display bold (700) normal,
* Dodany nowy obrazek z logo, żeby uniknąć wczytywania kolejnej czcionki
* Usunięte niepotrzebne fragmenty kodu CSS stylujące usunięte elementy HTML'a
* Usunięte komentarze z pliku HTML
---
Już wszystko powinno być dobrze. Projekt został scommitowany i spushowany do gałęzi feature-nav. Tak w sumie to podlinkowane są dwie czcionki, bo dwa ostatnie linki dotyczą tej samej tylko o różnej wadze i rodzaju. Mam nadzieję, że to już jest ostateczna wersja :)

---
Pozdrawiam,
Paweł Skwirowski

2018-02-22 11:41 UTC, maciekmp commented
Jest bardzo fajnie tylko nie mogę zrozumieć jednej rzeczy. Dlaczego jak kliknę na pozycję w menu to zoznacza się ona z szarym tłem i później jak scrolluję po stronie dalej jest szara?

2018-02-22 11:42 UTC, maciekmp approved these changes

2018-02-22 20:52 UTC, merged